#!/usr/bin/env python3
"""Run safe roster-wide high-recall source searches for repo-bug-audit.

This script creates search seeds only. It does not create submitted Bugs,
repo profiles, final knowledge, or coverage claims.
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
from collections import Counter, defaultdict
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


EXCLUDE_GLOBS = [
    "!.git/**",
    "!node_modules/**",
    "!dist/**",
    "!build/**",
    "!target/**",
    "!coverage/**",
    "!__pycache__/**",
    "!.pytest_cache/**",
    "!.mypy_cache/**",
    "!.ruff_cache/**",
    "!.tox/**",
    "!venv/**",
    "!.venv/**",
    "!*bug-audit*/**",
]
INCLUDE_GLOBS = [
    "*.c",
    "*.cc",
    "*.cpp",
    "*.cs",
    "*.go",
    "*.h",
    "*.hpp",
    "*.html",
    "*.java",
    "*.js",
    "*.jsx",
    "*.kt",
    "*.php",
    "*.py",
    "*.rb",
    "*.rs",
    "*.scala",
    "*.sh",
    "*.sql",
    "*.swift",
    "*.ts",
    "*.tsx",
    "*.vue",
    "*.yaml",
    "*.yml",
    "*.toml",
    "*.properties",
    "*.env",
    "Dockerfile",
    "Makefile",
    "package.json",
    "pom.xml",
    "build.gradle",
    "build.gradle.kts",
    "requirements.txt",
]


@dataclass(frozen=True)
class PatternSpec:
    category: str
    name: str
    pattern: str
    guidance: str


def load_patterns(path: Path) -> list[PatternSpec]:
    """Load search patterns from a JSON file generated by the LLM.

    Expected format:
    [
      {"category": "...", "name": "...", "pattern": "...", "guidance": "..."},
      ...
    ]
    """
    if not path.is_file():
        raise SystemExit(f"Patterns file not found: {path}. Generate it with the LLM before running this script.")
    data = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(data, dict):
        data = data.get("patterns", [])
    if not isinstance(data, list):
        raise SystemExit(f"Patterns file must be a JSON list or an object with a 'patterns' list: {path}")
    patterns = []
    for index, item in enumerate(data, 1):
        if not isinstance(item, dict):
            continue
        pattern = str(item.get("pattern", "")).strip()
        if not pattern:
            continue
        category = str(item.get("category") or "llm-gap").strip()
        name = str(item.get("name") or f"pattern-{index:02d}").strip()
        guidance = str(item.get("guidance") or "Trace the hit before promoting.").strip()
        patterns.append(PatternSpec(category=category, name=name, pattern=pattern, guidance=guidance))
    if not patterns:
        raise SystemExit(f"No valid patterns found in {path}")
    return patterns


def read_roots(path: Path) -> list[Path]:
    roots: list[Path] = []
    for raw in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        root = Path(line).expanduser().resolve()
        if root.is_dir():
            roots.append(root)
    return sorted(set(roots))


def load_inventory(path: Path | None) -> dict[str, dict[str, Any]]:
    if path is None or not path.is_file():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    repos = payload.get("repos")
    if not isinstance(repos, list):
        return {}
    by_path = {}
    for item in repos:
        if not isinstance(item, dict):
            continue
        repo_path = item.get("path")
        if isinstance(repo_path, str):
            by_path[str(Path(repo_path).expanduser().resolve())] = item
    return by_path


def repo_name(root: Path, inventory_by_path: dict[str, dict[str, Any]]) -> tuple[str, str]:
    item = inventory_by_path.get(str(root))
    if item:
        return str(item.get("name") or root.name), str(item.get("profile_name") or root.name)
    safe = re.sub(r"[^a-z0-9._-]+", "-", root.name.lower()).strip("-") or "repo"
    return root.name, safe


def run_rg_all(root: Path, patterns: list[PatternSpec], max_matches_per_category: int = 20) -> tuple[list[dict[str, Any]], list[str]]:
    if shutil.which("rg") is None:
        return [], ["rg not found"]
    hits: list[dict[str, Any]] = []
    seen: set[tuple[str, int, str]] = set()
    category_counts: defaultdict[str, int] = defaultdict(int)
    errors: list[str] = []
    for spec in patterns:
        if category_counts[spec.category] >= max_matches_per_category:
            continue
        command = [
            "rg",
            "--json",
            "--line-number",
            "--no-heading",
            "--hidden",
            "--ignore-case",
        ]
        for glob in INCLUDE_GLOBS:
            command.extend(["--glob", glob])
        for glob in EXCLUDE_GLOBS:
            command.extend(["--glob", glob])
        command.extend(["-e", spec.pattern, str(root)])
        process = subprocess.Popen(
            command,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
        )

        assert process.stdout is not None
        for raw in process.stdout:
            if category_counts[spec.category] >= max_matches_per_category:
                process.kill()
                break
            try:
                event = json.loads(raw)
            except json.JSONDecodeError:
                continue
            if event.get("type") != "match":
                continue
            data = event.get("data") if isinstance(event.get("data"), dict) else {}
            path_text = data.get("path", {}).get("text")
            line_number = data.get("line_number")
            lines_text = data.get("lines", {}).get("text", "").strip()
            if not isinstance(path_text, str) or not isinstance(line_number, int):
                continue
            try:
                rel_path = Path(path_text).resolve().relative_to(root).as_posix()
            except ValueError:
                rel_path = path_text
            key = (rel_path, line_number, spec.name)
            if key in seen:
                continue
            seen.add(key)
            category_counts[spec.category] += 1
            hits.append(
                {
                    "path": rel_path,
                    "line": line_number,
                    "text": lines_text[:240],
                    "pattern": spec.name,
                    "category": spec.category,
                    "guidance": spec.guidance,
                }
            )
        _stdout, stderr = process.communicate()
        if process.returncode not in {0, 1, -9}:
            detail = stderr.strip() or f"rg exited {process.returncode}"
            errors.append(f"{spec.name}: {detail}")
    return hits, errors


def render_markdown(payload: dict[str, Any]) -> str:
    lines = [
        "# High-recall Search Seeds",
        "",
        "These are broad static-search leads for repo-local exploration. They are not submitted Bugs.",
        "",
        "| Metric | Value |",
        "|---|---:|",
        f"| Repositories scanned | {payload['repo_count']} |",
        f"| Pattern categories | {len(payload['patterns'])} |",
        f"| Total seed hits | {payload['total_hits']} |",
        "",
        "## Category Totals",
        "",
        "| Category | Hits |",
        "|---|---:|",
    ]
    for category, count in sorted(payload["category_totals"].items()):
        lines.append(f"| `{category}` | {count} |")
    lines.extend(["", "## Repository Seeds", ""])
    for repo in payload["repos"]:
        lines.extend(
            [
                f"### {repo['repo']}",
                "",
                f"- Path: `{repo['path']}`",
                f"- Seed hits: `{repo['hit_count']}`",
                "",
            ]
        )
        if repo["errors"]:
            lines.append("- Scan errors: " + "; ".join(repo["errors"][:5]))
            lines.append("")
        if not repo["hits"]:
            lines.append("- No broad search seeds found. Use the repo profile and surface map to continue manually.")
            lines.append("")
            continue
        lines.extend(["| Category | Location | Search Seed | Follow-up |", "|---|---|---|---|"])
        for hit in repo["hits"][:40]:
            text = str(hit["text"]).replace("|", "\\|")
            lines.append(
                f"| `{hit['category']}` | `{hit['path']}:{hit['line']}` | {text} | {hit['guidance']} |"
            )
        if repo["hit_count"] > 40:
            lines.append(f"| ... | ... | {repo['hit_count'] - 40} additional hits omitted from Markdown sample | see JSON |")
        lines.append("")
    return "\n".join(lines) + "\n"


def render_shard_seeds(repo_payload: dict[str, Any]) -> str:
    lines = [
        f"# Search Seeds: {repo_payload['repo']}",
        "",
        "These hits are high-recall exploration seeds. Promote only after repo-local tracing and false-positive review.",
        "",
        "| Category | Location | Search Seed | Follow-up |",
        "|---|---|---|---|",
    ]
    if not repo_payload["hits"]:
        lines.append("| none | none | No broad search seeds found. | Continue with surface-map and hypothesis exploration. |")
        return "\n".join(lines) + "\n"
    for hit in repo_payload["hits"]:
        text = str(hit["text"]).replace("|", "\\|")
        lines.append(f"| `{hit['category']}` | `{hit['path']}:{hit['line']}` | {text} | {hit['guidance']} |")
    return "\n".join(lines) + "\n"


def collect(args: argparse.Namespace, patterns: list) -> dict[str, Any]:
    roots = read_roots(Path(args.scan_roots).expanduser().resolve())
    inventory = load_inventory(Path(args.inventory).expanduser().resolve() if args.inventory else None)
    repos: list[dict[str, Any]] = []
    category_totals: Counter[str] = Counter()
    pattern_totals: Counter[str] = Counter()

    for root in roots:
        display_name, profile_name = repo_name(root, inventory)
        max_hits = max(args.max_hits_per_category, 0)
        hits, errors = run_rg_all(root, patterns, max_matches_per_category=max_hits) if patterns and max_hits else ([], [])
        for hit in hits:
            category_totals[str(hit["category"])] += 1
            pattern_totals[str(hit["pattern"])] += 1
        repos.append(
            {
                "repo": display_name,
                "profile_name": profile_name,
                "path": str(root),
                "hit_count": len(hits),
                "hits": hits,
                "errors": errors,
            }
        )

    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "scan_roots_file": str(Path(args.scan_roots).expanduser().resolve()),
        "repo_count": len(repos),
        "total_hits": sum(repo["hit_count"] for repo in repos),
        "patterns": [
            {"category": spec.category, "name": spec.name, "pattern": spec.pattern, "guidance": spec.guidance}
            for spec in patterns
        ],
        "category_totals": dict(category_totals),
        "pattern_totals": dict(pattern_totals),
        "repos": repos,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Run LLM-generated search patterns across repositories")
    parser.add_argument("scan_roots", help="Path to work/scanner-output/repo-scan-roots.txt")
    parser.add_argument("--inventory", help="Optional work/scanner-output/repo-inventory.json for repo names")
    parser.add_argument("--output-json", required=True, help="Write high-recall scan JSON")
    parser.add_argument("--output-md", required=True, help="Write high-recall scan Markdown summary")
    parser.add_argument("--patterns-file", required=True, help="JSON file with LLM-generated search patterns")
    parser.add_argument("--output-shard-dir", help="Optional work/shards directory for per-shard search-seeds.md")
    parser.add_argument("--max-hits-per-category", type=int, default=20, help="Maximum hits per category per repo")
    args = parser.parse_args()
    patterns = load_patterns(Path(args.patterns_file).expanduser().resolve())

    payload = collect(args, patterns)
    output_json = Path(args.output_json).expanduser().resolve()
    output_md = Path(args.output_md).expanduser().resolve()
    output_json.parent.mkdir(parents=True, exist_ok=True)
    output_md.parent.mkdir(parents=True, exist_ok=True)
    output_json.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    output_md.write_text(render_markdown(payload), encoding="utf-8")

    if args.output_shard_dir:
        shard_dir = Path(args.output_shard_dir).expanduser().resolve()
        for repo in payload["repos"]:
            target = shard_dir / repo["profile_name"] / "search-seeds.md"
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(render_shard_seeds(repo), encoding="utf-8")

    print(f"Generated high-recall scan: {output_json}")
    print(f"Repositories scanned: {payload['repo_count']}")
    print(f"Search seed hits: {payload['total_hits']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
